version: '3.8'

services:
  fcwebapp:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    env_file:
      - path: .env
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync+restart
          path: ./fcwebapp
          target: /app/fcwebapp
          ignore:
            - __pycache__

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: fcwebapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fcwebapp
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
